export const IMG_CDN_URL = "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

export const restaurantList = [
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "657823",
        name: "Subway",
        uuid: "492afdf9-051b-4008-b54a-6fa0a77f7654",
        city: "1",
        area: "Kanakapura",
        totalRatingsString: "50+ ratings",
        cloudinaryImageId: "0bf19a82b109b40c2f5c56d00f071a33",
        cuisines: ["Salads", "Snacks", "Desserts", "Beverages"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        slaString: "31 MINS",
        lastMileTravel: 2.9000000953674316,
        slugs: {
          restaurant: "subway-near-shinag-mall-kanakapura-road",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "Ground Floor, No. 64, Kanakapura Rd, near Shinag Mall, South, Bengaluru, Karnataka",
        locality: "Near Shinag Mall",
        parentId: 2,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "20% off",
          shortDescriptionList: [
            {
              meta: "20% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "20% off up to ₹50 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "20% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "20% off up to ₹50 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2800,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2800,
          message: "",
          title: "Delivery Charge",
          amount: "2800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=6170409~p=1~eid=00000186-e401-50a5-0348-2e2800600161",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.9 kms",
        hasSurge: false,
        sla: {
          restaurantId: "657823",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          lastMileTravel: 2.9000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.8",
        totalRatings: 50,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "82962",
        name: "Kabab Mehal",
        uuid: "d63d910c-fcd7-46fb-a99e-c8c57fcc7225",
        city: "1",
        area: "Kanakapura Road",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "fdgfcrdbiljqlqmchdcy",
        cuisines: ["Chinese"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 45,
        minDeliveryTime: 45,
        maxDeliveryTime: 45,
        slaString: "45 MINS",
        lastMileTravel: 10.100000381469727,
        slugs: {
          restaurant: "kabab-mahal-kanakapura-road-test-prod-area",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "No.61/2A,63,64 Banashankari 5th Stage,Raghuvanahalli,kanakapura main road, Bangalore.",
        locality: "Raghuvanahalli",
        parentId: 5679,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 9000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 9000,
          message: "",
          title: "Delivery Charge",
          amount: "9000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "10.1 kms",
        hasSurge: false,
        sla: {
          restaurantId: "82962",
          deliveryTime: 45,
          minDeliveryTime: 45,
          maxDeliveryTime: 45,
          lastMileTravel: 10.100000381469727,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "648814",
        name: "Burger King",
        uuid: "67c648b6-114a-4274-94fd-bbb01d2bb24c",
        city: "1",
        area: "Kanakapura Road",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "49c2de336da7fe4e91345a622b7d7abd",
        cuisines: ["Burgers", "American"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 47,
        minDeliveryTime: 47,
        maxDeliveryTime: 47,
        slaString: "47 MINS",
        lastMileTravel: 11.800000190734863,
        slugs: {
          restaurant: "burger-king-forum-falcon-kanakapura-road",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "Burger King , 4th Floor,Kitchen No. 4F-402 , Forum Falcon city,No.31, Konankunte Village, Uttarahalli Hobli, Bangalore south Taluk, Bangalore-560062",
        locality: "Forum Falcon City Mall",
        parentId: 166,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FLAT120 off",
          shortDescriptionList: [
            {
              meta: "FLAT120 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT120 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "₹120 OFF",
          shortDescriptionList: [
            {
              meta: "Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FLAT120 off | Use FLATDEAL",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 9500,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 9500,
          message: "",
          title: "Delivery Charge",
          amount: "9500",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "11.8 kms",
        hasSurge: false,
        sla: {
          restaurantId: "648814",
          deliveryTime: 47,
          minDeliveryTime: 47,
          maxDeliveryTime: 47,
          lastMileTravel: 11.800000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.6",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "650918",
        name: "Eating Love",
        uuid: "2a26648d-15f8-4d3e-98e4-7e7ca57c020c",
        city: "1",
        area: "Kanakapura Road",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "fdba17c836c5bc5a9fcc40f575aad7f1",
        cuisines: ["Italian"],
        tags: [],
        costForTwo: 60000,
        costForTwoString: "₹600 FOR TWO",
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        slaString: "33 MINS",
        lastMileTravel: 2.5999999046325684,
        slugs: {
          restaurant: "eating-love-kanakapura-road-kanakapura-road",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "No. 158, Pirgal Square, Kanakapura Main Road, Bangalore, Bangalore South, Bangalore Urban, Karnataka-560082",
        locality: "Kanakapura Main Road",
        parentId: 21050,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "Flat ₹ 150 off",
          shortDescriptionList: [
            {
              meta: "Flat ₹ 150 off| Use GOURMET150",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "Flat ₹ 150 off| Use GOURMET150",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "₹150 OFF",
          shortDescriptionList: [
            {
              meta: "Use GOURMET150",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "Flat ₹ 150 off| Use GOURMET150",
              discountType: "Flat",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2800,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2800,
          message: "",
          title: "Delivery Charge",
          amount: "2800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=6048070~p=4~eid=00000186-e401-50a5-0348-2e2900600463",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "650918",
          deliveryTime: 33,
          minDeliveryTime: 33,
          maxDeliveryTime: 33,
          lastMileTravel: 2.5999999046325684,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.8",
        totalRatings: 20,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "347241",
        name: "KFC",
        uuid: "04b40739-6483-462f-b8ab-df3184675196",
        city: "1",
        area: "Kanakapura Road",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "bdcd233971b7c81bf77e1fa4471280eb",
        cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 40,
        minDeliveryTime: 40,
        maxDeliveryTime: 40,
        slaString: "40 MINS",
        lastMileTravel: 10.100000381469727,
        slugs: {
          restaurant: "kfc-kanakpura-kumaraswamy-layout-uttarahalli",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "KFC Royal Oak Kanakpura # 5 & 6, Doddakallasandra Village, Kanakapura Main Road,Hobli, Bangalore South Taluk,Bangalore",
        locality: "Doddakallasandra",
        parentId: 547,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 9000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 9000,
          message: "",
          title: "Delivery Charge",
          amount: "9000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "10.1 kms",
        hasSurge: false,
        sla: {
          restaurantId: "347241",
          deliveryTime: 40,
          minDeliveryTime: 40,
          maxDeliveryTime: 40,
          lastMileTravel: 10.100000381469727,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
  ];